server:
  port: ${PORT:8072}
  # leave this here
  context-path: /reservations

management:
  endpoints:
    web.exposure.include: '*'
  health:
    db.enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    non-secure-port: ${server.port:0}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
#    org.agilehandy.boot.autoconfigure: DEBUG

local:
  mongo:
    port: 8751

spring:
  application:
    name: reservations-service
  security:
    oauth2:
      client:
        registration:
          client-booking:
            provider: uaa
            client-name: Client Booking Exchange
            client-id: client-booking
            client-secret: secret
            scope: booking
            authorization-grant-type: client_credentials
        provider:
          uaa:
            token-uri: http://localhost:8099/uaa/oauth/token
            jwk-set-uri: http://localhost:8099/uaa/token_keys
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8099/uaa/token_keys