server:
  port: ${PORT:8071}
  # leave this here
  context-path: /flights

management:
  endpoints:
    web.exposure.include: '*'
  health:
    db.enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    non-secure-port: ${server.port:0}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
#    org.agilehandy.boot.autoconfigure: DEBUG

local:
  mongo:
    port: 8752

data:
  filepath: /flights.dat

spring:
  application:
    name: flights-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8099/uaa/token_keys
