server:
  port: ${PORT:8080}
  #leave this here
  context-path: /ui

management:
  endpoints:
    web.exposure.include: '*'
  health:
    db.enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    non-secure-port: ${server.port:0}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
#    org.agilehandy.boot.autoconfigure: DEBUG

spring:
  application:
    name: agency-web
  devtools:
    livereload:
      enabled: true
    restart:
      log-condition-evaluation-delta: true
      enabled: true
  thymeleaf:
    mode: HTML
    check-template: false
    cache: false
  security:
    oauth2:
      client:
        registration:
          login-client:
            client-id: login-client
            client-secret: secret
            client-authentication-method: basic
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            client-name: Login Client
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: uaa
          client-search:
            client-id: client-search
            client-secret: secret
            client-authentication-method: basic
            scope: search
            authorization-grant-type: client_credentials
            client-name: Client Flights Search
            provider: uaa
          client-reserve:
            client-id: client-reserve
            client-secret: secret
            client-authentication-method: basic
            scope: reserve
            authorization-grant-type: client_credentials
            client-name: Client Reservations
            provider: uaa
        provider:
          uaa:
            authorization-uri: http://localhost:8099/uaa/oauth/authorize
            token-uri: http://localhost:8099/uaa/oauth/token
            user-info-uri: http://localhost:8099/uaa/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8099/uaa/token_keys