server:
  port: ${PORT:8090}
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

eureka:
  instance:
    non-secure-port: ${server.port:0}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - HEAD
            - PUT
            - DELETE
            - PATH
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-912341.oktapreview.com/oauth2/default
          jwk-set-uri: https://dev-912341.oktapreview.com/oauth2/default/v1/keys