server:
  port: ${PORT:8080}
  context-path: /ui

eureka:
  instance:
    non-secure-port: ${server.port:0}

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      log-condition-evaluation-delta: true
      enabled: true
  thymeleaf:
    mode: HTML
    check-template: false
    cache: false
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: {client_id}
            client-secret: {client-secret}
            client-authentication-method: basic
            scope: openid profile email
            authorization-grant-type: authorization_code
            client-name: okta
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          okta:
            authorization-uri: https://[okta-account].oktapreview.com/oauth2/default/v1/authorize
            token-uri: https://[okta-account].oktapreview.com/oauth2/default/v1/token
            user-info-uri: https://[okta-account].oktapreview.com/oauth2/default/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://[okta-account].oktapreview.com/oauth2/default/v1/keys