server:
  port: ${PORT:8090}
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

eureka:
  instance:
    non-secure-port: ${server.port:0}

spring:
  cloud:
    gateway:
      routes:
      - id: flights_service_route
        uri: lb://flights-service
        predicates:
        - Path=/api/flights/**
        filters:
        - RewritePath= /api/flights/(?<segment>.*),/flights/$\{segment}
      - id: reservations_service_route
        uri: lb://reservations-service
        predicates:
        - Path=/api/reservations/**
        filters:
        - RewritePath= /api/reservations/(?<segment>.*),/reservations/$\{segment}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - HEAD
            - PUT
            - DELETE
            - PATH
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://[okta-account].oktapreview.com/oauth2/default
#          jwk-set-uri: https://[okta-account].oktapreview.com/oauth2/default/v1/keys