server:
  port: ${PORT:8071}
  context-path: /flights

local:
  mongo:
    port: 8752

data:
  filepath: /flights.dat

eureka:
  instance:
    non-secure-port: ${server.port:0}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8099/uaa/token_keys