server:
  port: ${PORT:8071}
  context-path: /flights

local:
  mongo:
    port: 8752

data:
  filepath: /flights.dat

eureka:
  instance:
    non-secure-port: ${server.port:0}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-912341.oktapreview.com/oauth2/default
#          jwk-set-uri: https://dev-912341.oktapreview.com/oauth2/default/v1/keys