server:
  port: ${PORT:8072}
  context-path: /reservations

local:
  mongo:
    port: 8751

eureka:
  instance:
    non-secure-port: ${server.port:0}

# reservations service uses client grant type (machine-to-machine)
# to communicate with the flights service
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-name: okta
            client-id: {client-id}
            client-secret: {client-secret}
            authorization-grant-type: client_credentials
            scope: internals
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          okta:
            authorization-uri: https://[okta-account].oktapreview.com/oauth2/default/v1/authorize
            token-uri: https://[okta-account].oktapreview.com/oauth2/default/v1/token
            user-info-uri: https://[okta-account].oktapreview.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://[okta-account].oktapreview.com/oauth2/default/v1/keys
      resourceserver:
        jwt:
          issuer-uri: https://[okta-account].oktapreview.com/oauth2/default
#          jwk-set-uri: https://[okta-account].oktapreview.com/oauth2/default/v1/keys