server:
  port: ${PORT:8072}
  context-path: /reservations

local:
  mongo:
    port: 8751

eureka:
  instance:
    non-secure-port: ${server.port:0}

# reservations service uses client grant type (machine-to-machine)
# to communicate with the flights service
spring:
  security:
    oauth2:
      client:
        registration:
          client-reservations-exchange:
            provider: uaa
            client-name: Client Booking Exchange
            client-id: client-booking
            client-secret: secret
            scope: seating
            authorization-grant-type: client_credentials
        provider:
          uaa:
            token-uri: http://localhost:8099/uaa/oauth/token
            jwk-set-uri: http://localhost:8099/uaa/token_keys
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8099/uaa/token_keys