server:
  port: ${PORT:8072}
  context-path: /reservations

local:
  mongo:
    port: 8751

eureka:
  instance:
    non-secure-port: ${server.port:0}

# reservations service uses client grant type (machine-to-machine)
# to communicate with the flights service
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oahdv52nncnedLAq0h7
            client-secret: yhQ7Cr_BhOmFt23svakKyFz6lnBuBoD3CxA9dtyD
            authorization-grant-type: client_credentials
        provider:
          okta:
            authorization-uri: https://dev-912341.oktapreview.com/oauth2/default/v1/authorize
            token-uri: https://dev-912341.oktapreview.com/oauth2/default/v1/token
            user-info-uri: https://dev-912341.oktapreview.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://dev-912341.oktapreview.com/oauth2/default/v1/keys
      resourceserver:
        jwt:
          issuer-uri: https://dev-912341.oktapreview.com/oauth2/default
          jwk-set-uri: https://dev-912341.oktapreview.com/oauth2/default/v1/keys